### ISSUE TITLE
Fix copy and paste

### ISSUE THREAD

**Issue by ouro-ouroboros** [EventStore/EventStore.UI#60] opened 2015-04-06 18:59 UTC
Selected text in the UI is unselected during screen refresh making it difficult to copy and paste data from the UI.

**Comment by nmehlei** [comment] 2015-04-08 11:35
Duplicate of: https://github.com/EventStore/EventStore.UI/issues/40

**Comment by gregoryyoung** [comment] 2015-04-08 11:40
I believe this is already fixed.

At least it appears to be fixed here tested on the event + stream pages

**Comment by gregoryyoung** [comment] 2015-04-08 11:42
Ah nm I got it when expanding json on stream browser

**Comment by pgermishuys** [comment] 2015-04-08 12:17
I will attempt to resolve this in the next couple of days.

**Comment by pgermishuys** [comment] 2015-04-09 18:40
In the branch copy-to-clipboard branch i've added a copy to clipboard button. This will copy the data from the event into the clipboard.

![image](https://cloud.githubusercontent.com/assets/1062417/7074020/d698e520-def7-11e4-84fd-1a3120a7795b.png)

**Comment by rcknight** [comment] 2015-04-17 09:15
This has been fixed now that pull #62 has been merged

**Closed by rcknight** 2015-04-17 09:15 UTC
Labels: bug
