### ISSUE TITLE
Paging $all stream causes error 

### ISSUE THREAD

**Issue by ianbattersby** [EventStore/EventStore.UI#85] opened 2015-09-17 11:15 UTC
1. Go to "Stream browser"
1. Do gotoStream for $all
1. Hit 'last'
1. Hit 'previous' 3 times

Browsers shows;
Red notification saying there has been an error

Console shows;
```
[15064,43,11:13:24.125] Error during processing ReadAllEventsForward request.
Log record at actual pos 87311 has too large length: 1635013492 bytes, while limit is 16777216 bytes. In chunk #0-0 (chunk-000000.
000000).
```

**Comment by pgermishuys** [comment] 2015-09-17 12:38
I cannot reproduce this,
However there is a fix in 3.3.0 that might also get rid of this issue.
https://github.com/EventStore/EventStore/commit/221c17baa24f075441f5ea35ca286dce04d45f45

**Comment by pgermishuys** [comment] 2015-09-21 16:53
Can you consistently reproduce this @ianbattersby?

**Comment by ianbattersby** [comment] 2015-09-24 10:15
I'm still not running 3.3.0 engine tbh, just the UI, but will do.

**Comment by ianbattersby** [comment] 2015-09-24 15:00
@pgermishuys - FYI; This still happens using EventStore v3.3.0 and EventStore.UI 3.3.0 branches.

1. Browse $all
1. Hit Last
1. Hit Previous
1. Hit Previous

Stream does not exist with;

```
[25756,38,14:59:18.504] Error during processing ReadAllEventsForward request.
Log record at actual pos 87311 has too large length: 1869770864 bytes, while limit is 16777216 bytes. In chunk #0-0 (chunk-000000.000000).
```

**Comment by pgermishuys** [comment] 2015-12-17 05:48
Fixed by https://github.com/EventStore/EventStore/pull/780

**Closed by pgermishuys** 2015-12-17 05:48 UTC
